//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_KogorevNikitaEvgenievich.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TournamentDB_421_KogorevNikitaEvgenievichEntities : DbContext
    {
        public TournamentDB_421_KogorevNikitaEvgenievichEntities()
            : base("name=TournamentDB_421_KogorevNikitaEvgenievichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Format> Format { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<MatchPlayers> MatchPlayers { get; set; }
        public virtual DbSet<MatchViewed> MatchViewed { get; set; }
        public virtual DbSet<Moderator> Moderator { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<TeamContent> TeamContent { get; set; }
        public virtual DbSet<Tournament> Tournament { get; set; }
        public virtual DbSet<Viewer> Viewer { get; set; }
    }
}
